### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mfoo**
I've made some changes today, the app now stands up to the monkey for much longer without crashing. Tested 750 events before getting bored.

Martin

### CODE REVIEW

**Comment by mfoo** [comment]
This is still outstanding, plus a further few commits from several days ago. Is something wrong?

**Comment by EddieRingle** [comment]
I think I've pulled all the commits that are needed (just realized you added the HTML encoding for diffs commit here), so I'm going to close this up.

**Comment by mfoo** [comment]
Excellent, thanks. My timetable is starting to get busier again now so my commit rate is going to take a hit, keep up the good work though.

**Comment by EddieRingle** [comment]
That's cool. I just released beta1 to the Market, seeing as all the major bugs seem to be eliminated.

**Pull request closed without merging**
